/** ISO 639-1 languages plus a few common profile variants. Search to pick; no custom values. */
export const LANGUAGES = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chamorro",
  "Chechen",
  "Chichewa",
  "Chinese",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Church Slavic",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi",
  "Dutch",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Fulah",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek",
  "Guarani",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kalaallisut",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu",
  "Kinyarwanda",
  "Komi",
  "Kongo",
  "Korean",
  "Kuanyama",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Limburgish",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Navajo",
  "Ndonga",
  "Nepali",
  "North Ndebele",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Occitan",
  "Odia",
  "Ojibwe",
  "Oromo",
  "Ossetian",
  "Pali",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Romansh",
  "Rundi",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Scottish Gaelic",
  "Serbian",
  "Shona",
  "Sichuan Yi",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "South Ndebele",
  "Southern Sotho",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tongan",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang",
  "Zulu",
  "American Sign Language",
  "British Sign Language",
  "Indian Sign Language",
] as const;

/** Builder/job-profile skills. Search to pick; no custom values. */
export const SKILLS = [
  // Programming languages
  "ABAP",
  "Ada",
  "Assembly",
  "Ballerina",
  "Bash",
  "C",
  "C#",
  "C++",
  "Clojure",
  "COBOL",
  "Crystal",
  "D",
  "Dart",
  "Delphi",
  "Elixir",
  "Elm",
  "Erlang",
  "F#",
  "Fortran",
  "Go",
  "Groovy",
  "Hack",
  "Haskell",
  "Haxe",
  "HTML",
  "Java",
  "JavaScript",
  "Julia",
  "Kotlin",
  "Lisp",
  "Lua",
  "MATLAB",
  "Nim",
  "Objective-C",
  "OCaml",
  "Pascal",
  "Perl",
  "PHP",
  "PowerShell",
  "Prolog",
  "Python",
  "R",
  "Racket",
  "Ruby",
  "Rust",
  "Scala",
  "Scheme",
  "Shell",
  "Solidity",
  "SQL",
  "Swift",
  "TypeScript",
  "VBA",
  "VB.NET",
  "Verilog",
  "VHDL",
  "Visual Basic",
  "WebAssembly",
  "Zig",
  "CSS",
  "Sass",
  "SCSS",
  "Less",
  "GraphQL",
  "JSON",
  "XML",
  "YAML",
  "Markdown",
  "Regex",

  // Frontend
  "React",
  "React Router",
  "Next.js",
  "Remix",
  "Astro",
  "Gatsby",
  "Vue",
  "Nuxt",
  "Angular",
  "Svelte",
  "SvelteKit",
  "SolidJS",
  "Qwik",
  "Ember",
  "Backbone.js",
  "jQuery",
  "Alpine.js",
  "HTMX",
  "Lit",
  "Preact",
  "Redux",
  "Redux Toolkit",
  "Zustand",
  "Jotai",
  "Recoil",
  "MobX",
  "Pinia",
  "Vuex",
  "NgRx",
  "TanStack Query",
  "SWR",
  "Apollo Client",
  "Relay",
  "tRPC",
  "React Hook Form",
  "Formik",
  "Zod",
  "Yup",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Mantine",
  "Chakra UI",
  "Ant Design",
  "shadcn/ui",
  "Radix UI",
  "Base UI",
  "Headless UI",
  "Styled Components",
  "Emotion",
  "CSS Modules",
  "PostCSS",
  "Three.js",
  "React Three Fiber",
  "D3.js",
  "Chart.js",
  "Recharts",
  "Framer Motion",
  "GSAP",
  "Storybook",
  "Webpack",
  "Vite",
  "esbuild",
  "Rollup",
  "Parcel",
  "Turbopack",
  "Babel",
  "SWC",
  "ESLint",
  "Prettier",
  "Biome",
  "pnpm",
  "npm",
  "Yarn",
  "Bun",
  "Nx",
  "Turborepo",
  "Lerna",

  // Backend
  "Node.js",
  "Express",
  "Fastify",
  "Koa",
  "Hono",
  "NestJS",
  "AdonisJS",
  "Deno",
  "Django",
  "Flask",
  "FastAPI",
  "Pyramid",
  "Tornado",
  "Spring",
  "Spring Boot",
  "Quarkus",
  "Micronaut",
  "Jakarta EE",
  "Laravel",
  "Symfony",
  "CodeIgniter",
  "CakePHP",
  "Ruby on Rails",
  "Sinatra",
  "ASP.NET",
  ".NET",
  ".NET Core",
  "Blazor",
  "Gin",
  "Echo",
  "Fiber",
  "Chi",
  "Actix",
  "Axum",
  "Rocket",
  "Phoenix",
  "Play Framework",
  "Akka",
  "Ktor",
  "gRPC",
  "Connect RPC",
  "REST APIs",
  "SOAP",
  "WebSockets",
  "Socket.IO",
  "Server-Sent Events",
  "OpenAPI",
  "Swagger",
  "OAuth",
  "OIDC",
  "JWT",
  "SAML",
  "Auth0",
  "Clerk",
  "NextAuth",
  "Keycloak",
  "Passport.js",

  // Mobile
  "Android",
  "iOS",
  "React Native",
  "Expo",
  "Flutter",
  "SwiftUI",
  "UIKit",
  "Jetpack Compose",
  "Kotlin Multiplatform",
  "Ionic",
  "Capacitor",
  "Cordova",
  "Xamarin",
  ".NET MAUI",
  "NativeScript",

  // Data & databases
  "PostgreSQL",
  "MySQL",
  "MariaDB",
  "SQLite",
  "SQL Server",
  "Oracle Database",
  "MongoDB",
  "Redis",
  "Memcached",
  "Elasticsearch",
  "OpenSearch",
  "Solr",
  "Cassandra",
  "CouchDB",
  "Couchbase",
  "DynamoDB",
  "Cosmos DB",
  "Firestore",
  "Firebase Realtime Database",
  "Neo4j",
  "Amazon Neptune",
  "Snowflake",
  "BigQuery",
  "Redshift",
  "ClickHouse",
  "DuckDB",
  "Apache Hive",
  "Apache HBase",
  "InfluxDB",
  "TimescaleDB",
  "Prometheus",
  "Grafana Loki",
  "PlanetScale",
  "Supabase",
  "Firebase",
  "Neon",
  "Turso",
  "CockroachDB",
  "TiDB",
  "Prisma",
  "Drizzle",
  "TypeORM",
  "Sequelize",
  "Knex",
  "SQLAlchemy",
  "Hibernate",
  "Entity Framework",
  "Mongoose",
  "MikroORM",
  "Kysely",
  "Hasura",
  "PostgREST",

  // Cloud & DevOps
  "AWS",
  "Amazon EC2",
  "Amazon S3",
  "Amazon RDS",
  "Amazon ECS",
  "Amazon EKS",
  "Amazon Lambda",
  "Amazon SQS",
  "Amazon SNS",
  "Amazon CloudFront",
  "AWS CDK",
  "Google Cloud",
  "GCP Cloud Run",
  "GCP GKE",
  "Azure",
  "Azure Functions",
  "Azure DevOps",
  "Cloudflare",
  "Cloudflare Workers",
  "Vercel",
  "Netlify",
  "Railway",
  "Render",
  "Fly.io",
  "Heroku",
  "DigitalOcean",
  "Linode",
  "Docker",
  "Podman",
  "Kubernetes",
  "Helm",
  "Kustomize",
  "Terraform",
  "OpenTofu",
  "Pulumi",
  "Ansible",
  "Chef",
  "Puppet",
  "Packer",
  "Vagrant",
  "Nginx",
  "Apache HTTP Server",
  "Caddy",
  "HAProxy",
  "Linux",
  "Ubuntu",
  "Debian",
  "CentOS",
  "RHEL",
  "Alpine Linux",
  "Windows Server",
  "macOS",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "Buildkite",
  "Argo CD",
  "Flux",
  "Spinnaker",
  "Prometheus",
  "Grafana",
  "Datadog",
  "New Relic",
  "Sentry",
  "OpenTelemetry",
  "Jaeger",
  "Zipkin",
  "ELK Stack",
  "Splunk",
  "PagerDuty",
  "CI/CD",
  "DevOps",
  "SRE",
  "Platform Engineering",
  "Infrastructure as Code",
  "Observability",
  "Site Reliability",

  // Data, ML, AI
  "Pandas",
  "NumPy",
  "SciPy",
  "Polars",
  "Spark",
  "PySpark",
  "Hadoop",
  "Kafka",
  "Redpanda",
  "RabbitMQ",
  "ActiveMQ",
  "NATS",
  "Apache Flink",
  "Apache Beam",
  "Airflow",
  "Dagster",
  "Prefect",
  "dbt",
  "Looker",
  "Tableau",
  "Power BI",
  "Metabase",
  "Superset",
  "Excel",
  "Google Sheets",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "JAX",
  "scikit-learn",
  "XGBoost",
  "LightGBM",
  "Hugging Face",
  "Transformers",
  "LangChain",
  "LlamaIndex",
  "OpenAI",
  "Anthropic",
  "Gemini",
  "Mistral",
  "Ollama",
  "vLLM",
  "RAG",
  "Prompt Engineering",
  "Fine-tuning",
  "LoRA",
  "Computer Vision",
  "OpenCV",
  "NLP",
  "spaCy",
  "NLTK",
  "Speech Recognition",
  "Recommendation Systems",
  "Time Series",
  "MLOps",
  "MLflow",
  "Weights & Biases",
  "Kubeflow",
  "Feature Stores",
  "CUDA",
  "ONNX",
  "Data Analysis",
  "Data Engineering",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "LLMs",
  "Statistics",
  "A/B Testing",

  // Testing & quality
  "Jest",
  "Vitest",
  "Mocha",
  "Chai",
  "Jasmine",
  "Testing Library",
  "Cypress",
  "Playwright",
  "Selenium",
  "Puppeteer",
  "Appium",
  "Detox",
  "Storybook Testing",
  "MSW",
  "Supertest",
  "JUnit",
  "TestNG",
  "Mockito",
  "PyTest",
  "unittest",
  "RSpec",
  "PHPUnit",
  "xUnit",
  "NUnit",
  "k6",
  "JMeter",
  "Postman",
  "Insomnia",
  "Bruno",
  "Pact",
  "TDD",
  "BDD",
  "Unit Testing",
  "Integration Testing",
  "E2E Testing",
  "Load Testing",
  "QA",
  "Manual Testing",
  "Test Automation",

  // Design & product
  "Figma",
  "Sketch",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe After Effects",
  "Framer",
  "Webflow",
  "Canva",
  "UI Design",
  "UX Design",
  "Product Design",
  "Interaction Design",
  "Visual Design",
  "Design Systems",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Usability Testing",
  "Accessibility",
  "WCAG",
  "Inclusive Design",
  "Information Architecture",
  "Product Management",
  "Product Strategy",
  "Roadmapping",
  "User Stories",
  "Agile",
  "Scrum",
  "Kanban",
  "Lean",
  "OKRs",
  "Jira",
  "Linear",
  "Asana",
  "Trello",
  "Notion",
  "Confluence",
  "Miro",
  "FigJam",

  // Security, architecture, other
  "Cybersecurity",
  "Application Security",
  "Network Security",
  "Penetration Testing",
  "OWASP",
  "Cryptography",
  "IAM",
  "Zero Trust",
  "SOC 2",
  "GDPR",
  "System Design",
  "Distributed Systems",
  "Microservices",
  "Monoliths",
  "Event-Driven Architecture",
  "Domain-Driven Design",
  "CQRS",
  "Event Sourcing",
  "API Design",
  "Software Architecture",
  "Design Patterns",
  "Data Structures",
  "Algorithms",
  "Competitive Programming",
  "Low-Level Design",
  "High-Level Design",
  "Performance Optimization",
  "Caching",
  "Message Queues",
  "Search",
  "Payments",
  "Stripe",
  "PayPal",
  "Razorpay",
  "Shopify",
  "WordPress",
  "Webflow CMS",
  "Contentful",
  "Sanity",
  "Strapi",
  "SEO",
  "Google Analytics",
  "Mixpanel",
  "Amplitude",
  "Segment",
  "Hotjar",
  "Growth",
  "Technical Writing",
  "Developer Relations",
  "Mentoring",
  "Leadership",
  "Team Lead",
  "Engineering Management",
  "Staff Engineering",
  "Public Speaking",
  "Blockchain",
  "Ethereum",
  "Smart Contracts",
  "Web3",
  "Unity",
  "Unreal Engine",
  "Godot",
  "Game Development",
  "AR",
  "VR",
  "IoT",
  "Embedded Systems",
  "Robotics",
  "Salesforce",
  "SAP",
  "ServiceNow",
  "Workday",
  "Zapier",
  "n8n",
  "Make",
] as const;

export const LANGUAGE_SET = new Set<string>(LANGUAGES);
export const SKILL_SET = new Set<string>(SKILLS);

export const LANGUAGE_OPTIONS = [...LANGUAGE_SET].sort((a, b) =>
  a.localeCompare(b),
);
export const SKILL_OPTIONS = [...SKILL_SET].sort((a, b) =>
  a.localeCompare(b),
);
